import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:meamore_shared/l10n/app_localizations.dart';

import 'package:meamore_shared/app_locale.dart';
import 'firebase_options.dart'; // generated by flutterfire for THIS app
import 'pages/employee_id_page.dart';
import 'pages/home_page.dart';
import 'storage/employee_identity_store.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await AppLocale.init(); // use the last choosen language
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const EmployeeApp());
}

class EmployeeApp extends StatelessWidget {
  const EmployeeApp({super.key});

  static const String shopId = 'meamore';

  Future<String> _initialRoute() async {
    final id = await EmployeeIdentityStore().getEmployeeId();
    return (id == null) ? '/employeeId' : '/home';
  }

  @override
  Widget build(BuildContext context) {
    final scheme = ColorScheme.fromSeed(seedColor: Colors.teal);
    return ValueListenableBuilder<Locale>(
      valueListenable: AppLocale.overrideLocale,
      builder: (_, locale, __) {
        return MaterialApp(
          theme: ThemeData(
            useMaterial3: true,
            colorScheme: scheme,
            scaffoldBackgroundColor: scheme.surfaceContainerLowest,
            dividerColor: scheme.outlineVariant,
            dividerTheme: DividerThemeData(color: scheme.outlineVariant),
            appBarTheme: AppBarTheme(
              backgroundColor: scheme.surface,
              foregroundColor: scheme.onSurface,
              elevation: 0,
              centerTitle: true,
            ),
            cardTheme: CardThemeData(
              elevation: 0,
              color: scheme.surface,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(16),
                side: BorderSide(color: scheme.outlineVariant),
              ),
            ),
            chipTheme: ChipThemeData(
              backgroundColor: scheme.surfaceContainerHighest,
              selectedColor: scheme.secondaryContainer,
              disabledColor: scheme.surfaceContainerHighest,
              labelStyle: TextStyle(color: scheme.onSurfaceVariant),
              secondaryLabelStyle: TextStyle(color: scheme.onSecondaryContainer),
              padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 6),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(999),
                side: BorderSide(color: scheme.outlineVariant),
              ),
            ),
          ),
          debugShowCheckedModeBanner: false,
          title: 'Employee App',
          locale: locale,
          supportedLocales: AppLocalizations.supportedLocales,
          localizationsDelegates: const [
            AppLocalizations.delegate,
            GlobalMaterialLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
            GlobalCupertinoLocalizations.delegate,
          ],
          home: FutureBuilder<String>(
            future: _initialRoute(),
            builder: (context, snap) {
              if (!snap.hasData) {
                return const Directionality(
                  textDirection: TextDirection.ltr,
                  child: Material(
                    child: Center(child: CircularProgressIndicator()),
                  ),
                );
              }
              final route = snap.data!;
              if (route == '/employeeId') return const EmployeeIdPage();
              return const HomePage(shopId: shopId);
            },
          ),
          routes: {
            '/employeeId': (_) => const EmployeeIdPage(),
            '/home': (_) => const HomePage(shopId: shopId),
          },
        );
      },
    );
  }
}
