// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCPnUjoJzykno-AmgUs-U5D3AFzedH3_s',
    appId: '1:401676264830:web:6c3c8e48859d8078723f2f',
    messagingSenderId: '401676264830',
    projectId: 'me-amore-employees',
    authDomain: 'me-amore-employees.firebaseapp.com',
    storageBucket: 'me-amore-employees.firebasestorage.app',
    measurementId: 'G-14GV8V6WN0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDTyF0sCye1ZOw2mCQywuilT6sO1zFc3M',
    appId: '1:401676264830:android:973a783239d1808d723f2f',
    messagingSenderId: '401676264830',
    projectId: 'me-amore-employees',
    storageBucket: 'me-amore-employees.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkPVvnvcf-cvvr8cFxn83JKixIupOAcdc',
    appId: '1:401676264830:ios:05e9ce674e43783a723f2f',
    messagingSenderId: '401676264830',
    projectId: 'me-amore-employees',
    storageBucket: 'me-amore-employees.firebasestorage.app',
    iosBundleId: 'com.meamore.meamore',
  );

}